03-22 12:43:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "UPDATED_RESOURCES" not found; SQL statement:
delete from UPDATED_RESOURCES [42102-153]
03-22 12:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UPDATED_RESOURCES" not found; SQL statement:
delete from UPDATED_RESOURCES [42102-153]
03-22 12:43:51 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "UPDATED_RESOURCES" not found; SQL statement:
delete from UPDATED_RESOURCES [42102-153]
03-22 12:44:30 jdbc[3]: The connection was not closed by the application and is garbage collected [90018-153]
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:98)
	at org.h2.Driver.connect(Driver.java:72)
	at net.ontopia.topicmaps.utils.sdshare.client.JDBCQueueBackend.getConnection(JDBCQueueBackend.java:142)
	at net.ontopia.topicmaps.utils.sdshare.client.JDBCQueueBackend.applyFragments(JDBCQueueBackend.java:60)
	at net.ontopia.topicmaps.utils.sdshare.client.test.JDBCQueueBackendTest.testEmpty(JDBCQueueBackendTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
03-22 12:44:39 jdbc[7]: The connection was not closed by the application and is garbage collected [90018-153]
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:98)
	at org.h2.Driver.connect(Driver.java:72)
	at net.ontopia.topicmaps.utils.sdshare.client.JDBCQueueBackend.getConnection(JDBCQueueBackend.java:142)
	at net.ontopia.topicmaps.utils.sdshare.client.JDBCQueueBackend.applyFragments(JDBCQueueBackend.java:60)
	at net.ontopia.topicmaps.utils.sdshare.client.test.JDBCQueueBackendTest.testChooseRightSyntax(JDBCQueueBackendTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
